name: Run Azure Login with OpenID Connect
on: [push]

permissions:
      id-token: write
      contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./primary/network

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./primary/network


